// Constants for the language server
export const LANGUAGE_ID = 'nsm';

// Regular expressions for various parts of the NSM language
export const BLOCK_COMMENT_PATTERN = /\/\*[\s\S]*?\*\/|([^\\:]|^)\/\/.*$/gm;
export const LINE_COMMENT_PATTERN = /#.*/g;
export const DOUBLE_QUOTED_STRING_PATTERN = /"([^"\\]*(\\.[^"\\]*)*)"/g;
export const CONFIG_SECTION_NAME = 'nsmLanguageServer';
export const MOLECULE_PATTERN =
  /\"\"\"[ \t]*([a-zA-Z0-9_]+)[ \t]*\n+([a-zA-Z0-9_\n ]+)\n\"\"\"/g;

export const grammarWords = new Set([
  'A LONG TIME',
  'A SHORT TIME',
  'ABOVE',
  'AFTER',
  'ALL',
  'AND',
  'ANOTHER',
  'AS',
  'BAD',
  'BE',
  'BE',
  'BECAUSE',
  'BEFORE',
  'BELOW',
  'BIG',
  'BODY',
  'BY',
  'CAN',
  'DIE',
  'DO',
  "DON'T WANT",
  'ELSE',
  'FAR',
  'FEEL',
  'FEW',
  'FOR SOME TIME',
  'GOOD',
  'HAPPEN',
  'HEAR',
  'HERE',
  'I',
  'IF',
  'INSIDE',
  'KIND',
  'KNOW',
  'LESS',
  'LIKE',
  'LITTLE',
  'LIVE',
  'MANY',
  'MAYBE',
  'MINE',
  'MOMENT',
  'MORE',
  'MOVE',
  'MUCH',
  'MUST',
  'NEAR',
  'NOT',
  'NOW',
  'OF',
  'ONE',
  'OR',
  'OTHER',
  'PART',
  'PEOPLE',
  'SAY',
  'SEE',
  'SHOULD',
  'SIDE',
  'SMALL',
  'SO',
  'SOME',
  'SOMEONE',
  'SOMETHING',
  'THAN',
  'THAT',
  'THE SAME',
  'THERE IS',
  'THING',
  'THINK',
  'THIS',
  'TOUCH',
  'TRUE',
  'TWO',
  'VERY',
  'WANT',
  'WAY',
  'WHEN',
  'WHERE',
  'WORD',
  'YOU',
]);

// This is an example configuration for the NSM language
export const NSM_CONFIGURATION = {
  wordPattern: MOLECULE_PATTERN,
  indentationRules: {
    // The language's indentation settings
    increaseIndentPattern: /^.*\{$/,
    decreaseIndentPattern: /^\}/,
  },
  brackets: [
    ['{', '}'],
    ['[', ']'],
    ['(', ')'],
  ],
  autoClosingPairs: [
    { open: '{', close: '}' },
    { open: '[', close: ']' },
    { open: '(', close: ')' },
    { open: '"', close: '"' },
  ],
};
